namespace LanePets.Models;

public class Pet { public string Id { get; set; } = ""; public string Dono { get; set; } = ""; public string PetNome { get; set; } = ""; public string Tipo { get; set; } = ""; public string Raca { get; set; } = ""; public string Telefone { get; set; } = ""; public string Endereco { get; set; } = ""; public string PacoteJson { get; set; } = ""; public string Unidade { get; set; } = ""; public string ClienteId { get; set; } = ""; }
public class Cliente { public string Id { get; set; } = ""; public string Nome { get; set; } = ""; public string Telefone { get; set; } = ""; public string Endereco { get; set; } = ""; public string Observacoes { get; set; } = ""; public string Origem { get; set; } = ""; public string Status { get; set; } = ""; }
public class Agendamento { public string Id { get; set; } = ""; public string Pet { get; set; } = ""; public string Dono { get; set; } = ""; public string Telefone { get; set; } = ""; public string DataHora { get; set; } = ""; public string ServicosJson { get; set; } = "[]"; public decimal Total { get; set; } public string Transporte { get; set; } = ""; public decimal ValorTransporte { get; set; } public string Status { get; set; } = ""; public string PagamentoStatus { get; set; } = ""; public string FormaPagamento { get; set; } = ""; public string Obs { get; set; } = ""; public string Unidade { get; set; } = ""; public string ClienteId { get; set; } = ""; public string PetId { get; set; } = ""; }
public class Servico { public string Id { get; set; } = ""; public string Nome { get; set; } = ""; public decimal Preco { get; set; } public string Porte { get; set; } = ""; public string AdicionaisJson { get; set; } = "[]"; public string Pacote { get; set; } = ""; public string Adicional { get; set; } = ""; }
public class Produto { public string Id { get; set; } = ""; public string Codigo { get; set; } = ""; public string Nome { get; set; } = ""; public string Categoria { get; set; } = ""; public decimal ValorCompra { get; set; } public decimal ValorVenda { get; set; } }
public class EntradaSaida { public string Id { get; set; } = ""; public string Data { get; set; } = ""; public string Descricao { get; set; } = ""; public string Tipo { get; set; } = ""; public decimal Valor { get; set; } public string Unidade { get; set; } = ""; public string Origem { get; set; } = ""; }
public class Pacote { public string Id { get; set; } = ""; public string PetId { get; set; } = ""; public string Cliente { get; set; } = ""; public string Tipo { get; set; } = ""; public int Quantidade { get; set; } public int Utilizados { get; set; } public int Restantes { get; set; } public string DataInicio { get; set; } = ""; public string DataFim { get; set; } = ""; public string Status { get; set; } = ""; public string Unidade { get; set; } = ""; }
public class Configuracao { public string Chave { get; set; } = ""; public string Valor { get; set; } = ""; public string Descricao { get; set; } = ""; }
public class Auditoria { public string Id { get; set; } = ""; public DateTime DataHora { get; set; } public string Acao { get; set; } = ""; public string Entidade { get; set; } = ""; public string RegistroId { get; set; } = ""; public string Detalhes { get; set; } = ""; }
public class AuditoriaMigracao { public string Id { get; set; } = ""; public DateTime DataHora { get; set; } public string Tipo { get; set; } = ""; public string Entidade { get; set; } = ""; public string RegistroId { get; set; } = ""; public string Status { get; set; } = ""; public string Descricao { get; set; } = ""; public string ValorOriginal { get; set; } = ""; public string ValorSugerido { get; set; } = ""; }
public class ReconciliacaoMigracao { public string Id { get; set; } = ""; public DateTime DataHora { get; set; } public string AgendamentoId { get; set; } = ""; public string DonoHistorico { get; set; } = ""; public string PetHistorico { get; set; } = ""; public string TelefoneHistorico { get; set; } = ""; public string Classificacao { get; set; } = ""; public int Pontuacao { get; set; } public string CandidatoPetId { get; set; } = ""; public string CandidatoDono { get; set; } = ""; public string CandidatoPet { get; set; } = ""; public string CandidatoTelefone { get; set; } = ""; public string CandidatoClienteId { get; set; } = ""; public string Motivo { get; set; } = ""; public string SegundoCandidato { get; set; } = ""; public string AcaoRecomendada { get; set; } = ""; public string Observacao { get; set; } = ""; public string Status { get; set; } = ""; }
public class Depoimento { public string Id { get; set; } = ""; public string ClienteId { get; set; } = ""; public string NomeCliente { get; set; } = ""; public string NomePet { get; set; } = ""; public string Telefone { get; set; } = ""; public int Avaliacao { get; set; } public string Comentario { get; set; } = ""; public string Status { get; set; } = "Pendente"; public DateTime CriadoEm { get; set; } = DateTime.UtcNow; }
public class PlanoSeguro { public string Id { get; set; } = ""; public string Nome { get; set; } = ""; public string Descricao { get; set; } = ""; public string Coberturas { get; set; } = ""; public string Beneficios { get; set; } = ""; public decimal ValorMensal { get; set; } public bool Ativo { get; set; } = true; }
public class SolicitacaoSeguro { public string Id { get; set; } = ""; public string PlanoSeguroId { get; set; } = ""; public string NomePlano { get; set; } = ""; public string NomeCliente { get; set; } = ""; public string Telefone { get; set; } = ""; public string NomePet { get; set; } = ""; public string Observacao { get; set; } = ""; public string Status { get; set; } = "Pendente"; public DateTime CriadoEm { get; set; } = DateTime.UtcNow; }
public class UsuarioCliente { public string Id { get; set; } = ""; public string ClienteId { get; set; } = ""; public string Email { get; set; } = ""; public string SenhaHash { get; set; } = ""; public string SenhaSalt { get; set; } = ""; public DateTime CriadoEm { get; set; } = DateTime.UtcNow; }
public class UsuarioAdministrador { public string Id { get; set; } = ""; public string Email { get; set; } = ""; public string SenhaHash { get; set; } = ""; public string SenhaSalt { get; set; } = ""; public bool Ativo { get; set; } = true; public DateTime CriadoEm { get; set; } = DateTime.UtcNow; }
public class Unidade { public string Id { get; set; } = ""; public string Nome { get; set; } = ""; public string Endereco { get; set; } = ""; public string Telefone { get; set; } = ""; public string HorarioFuncionamento { get; set; } = ""; public bool Ativa { get; set; } = true; }
public class Pedido { public string Id { get; set; } = ""; public string ClienteId { get; set; } = ""; public string ProdutoId { get; set; } = ""; public string ProdutoNome { get; set; } = ""; public int Quantidade { get; set; } public decimal Total { get; set; } public string FormaPagamento { get; set; } = ""; public string Status { get; set; } = "Pendente"; public DateTime CriadoEm { get; set; } = DateTime.UtcNow; }
